### PR TITLE
switched all tests to aioresponses

### PR DESCRIPTION
**Pull request by etsinko**

### CODE REVIEW

**Comment by sander76** [comment]
@etsinko Can't I just give you full rights to this repo so you have more control ?
I guess you're the more experienced coder. It will benefit the project.

Sander.

**Comment by etsinko** [comment]
Sure, if you think it is better. I'm ok with either PRs or having access to the repo.

**Comment by etsinko** [comment]
@sander76 are you planning to merge this PR? I also thought about adding Travis CI and Coverals integrations to testing is automatically taken care of.

**Comment by sander76** [comment]
@etsinko Just gave you collaborator rights. My free time to work on this comes in waves.... A bit short on time now. Don't want to slow you down.... Please let me if this works for you..

**Comment by etsinko** [comment]
@sander76 yes this works for me. Thank you!

**Pull request merged**
