### PR TITLE
Fix various unit tests

### PR DESCRIPTION
**Pull request by robert-alfaro**
Contributing fixes against #32

### CODE REVIEW

**Comment by robert-alfaro** [comment]
All unit tests pass - tested with min req python 3.11.

**Comment by robert-alfaro** [comment]
@kingy444 @sander76 @bdraco anything else required for next steps (ultimately getting HA side updated)?

**Comment by kingy444** [comment]
Nothing here is holding up HA side. There was just a large refactor for v3 of this library to work.

That will get merged pretty soon then I can get to next steps of adding and improving functionality.

Appreciate your time fixing the tests, that will save me time for sure and that is a huge help

All the HA code is done. The core functionality has finished its review with the HA team and will move to dev branch soon. 
Then I will revisit my old code for the extended functionality, refactor and resubmit (each PR needs to have one intended purpose)

ie. I cannot submit a PR that adds Velocity functionality and also addresses some timeout issues. Code for both of those is done. But I need the current branch merged before I can submit the next

**Comment by robert-alfaro** [comment]
ah, I misunderstood these tests were holding up [one or more] PRs on the HA side. Thanks for clarifying..glad to have helped with something.

**Pull request merged**
