### PR TITLE
WIP: Cleanups / updates

### PR DESCRIPTION
**Pull request by etsinko**
Moved everything to Python 3.5 syntax and cleaned up some code.

### CODE REVIEW

**Comment by sander76** [comment]
@etsinko Thanks man! Recently I was told not to be using the async def syntax in combination with home assistant yet. So I guess I'll merge this into a separate branch so we can use it later on.

**Comment by etsinko** [comment]
@sander76 You are welcome! 
As far as I know home assistant dropped python 3.4 support as of version 0.55: https://home-assistant.io/blog/2017/10/06/deprecating-python-3.4-support/
I assumed that it was ok to use async def / wait since 0.55

**Comment by sander76** [comment]
@etsinko yeah I thought so too. I went on discord and got an answer from balloob (the creator of hass). Python 3.4 support is dropped, but hass itself will move to async def and await syntax around January. Before that using async def is not advised...

**Comment by etsinko** [comment]
@sander76 Ok, that I didn't know. I will revert async def / wait changes for now and will add some more cleanups / updates if you are ok with that.

**Comment by sander76** [comment]
@etsinko by all means!

**Comment by sander76** [comment]
@etsinko I just updated the hass plugin. Will do a pr later this week. So you should be able to integrate powerview with the next hass release

**Comment by etsinko** [comment]
@sander76 is your last comment regarding typo in `sceneid`?

**Comment by sander76** [comment]
@etsinko yes. I found out I actually fixed that earlier. Sorry about that. But I needed to update hass plugin to use that later version...

**Comment by etsinko** [comment]
No prob, I'll keep adding changes to this PR then.

**Pull request merged**
